http:
  routers:
    traefik:
      rule: "Host(`traefik.docker.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
          - main: "app.test"
            sans:
              - "*.app.test"
          - main: "mailhog.test"
            sans:
              - "*.mailhog.test"
          - main: "redis.test"
            sans:
              - "*.redis.test"
          - main: "mysql.test"
            sans:
              - "*.mysql.test"
          - main: "wp.test"
            sans:
              - "*.wp.test"
          - main: "localhost"
            sans:
              - "*.localhost"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
